apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: default
data:
  MONGODB_URI: "mongodb://mongo-service:27017/todos"
  ELASTICSEARCH_NODE: "http://elasticsearch-service:9200"
  PORT: "3001"
  NODE_ENV: "production"
  CORS_ORIGIN: "http://localhost:3000"

